--liquibase formatted sql

--changeset mikhailRogov:1
INSERT INTO I_QUESTION_IMPORTANCE (`ID`,`WEIGHT`) VALUES (1,100);
INSERT INTO I_QUESTION_IMPORTANCE (`ID`,`WEIGHT`) VALUES (2,10);
INSERT INTO I_QUESTION_IMPORTANCE (`ID`,`WEIGHT`) VALUES (3,1);
INSERT INTO I_QUESTION_IMPORTANCE (`ID`,`WEIGHT`) VALUES (4,0);
--changeset mikhailRogov:2
INSERT INTO I_QUESTION_EXTENDED (`ID`) VALUES(1);
INSERT INTO I_QUESTION_EXTENDED (`ID`) VALUES(2);
INSERT INTO I_QUESTION_EXTENDED (`ID`) VALUES(3);
INSERT INTO I_QUESTION_EXTENDED (`ID`) VALUES(4);
--changeset mikhailRogov:3
INSERT INTO I_QUESTION_EXTENDED_LOCALE (`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(1,1,'Choose your religion');
INSERT INTO I_QUESTION_EXTENDED_LOCALE (`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(2,1,'Choose your political view');
INSERT INTO I_QUESTION_EXTENDED_LOCALE (`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(3,1,'Choose your gastronomical orientation');
INSERT INTO I_QUESTION_EXTENDED_LOCALE (`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(4,1,'What describes you the best');

INSERT INTO I_QUESTION_EXTENDED_LOCALE (`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(1,2,'Выберите вашу религию');
INSERT INTO I_QUESTION_EXTENDED_LOCALE (`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(2,2,'Укажите ваши политические взгляды');
INSERT INTO I_QUESTION_EXTENDED_LOCALE (`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(3,2,'Ваши предпочтения в еде');
INSERT INTO I_QUESTION_EXTENDED_LOCALE (`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(4,2,'Какой пункт вас описывает лучше всего');
--changeset mikhailRogov:4
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(1,1);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(2,1);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(3,1);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(4,1);

INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(5,2);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(6,2);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(7,2);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(8,2);

INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(9,3);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(10,3);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(11,3);

INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(12,4);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(13,4);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(14,4);
INSERT INTO I_ANSWER_EXTENDED (`ID`,`QUESTION_ID`) VALUES(15,4);
--changeset mikhailRogov:5
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(1,1,'Judaism');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(2,1,'Christianity');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(3,1,'Islam');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(4,1,'Ateism');

INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(1,2,'Иудаизм');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(2,2,'Христианство');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(3,2,'Ислам');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(4,2,'Атеизм');
--changeset mikhailRogov:6
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(5,1,'Left');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(6,1,'Right');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(7,1,'Trying to find golden mean');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(8,1,'Does not matter');

INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(5,2,'Левые');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(6,2,'Правые');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(7,2,'Пытаюсь найти золотую середину');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(8,2,'Не имеет значение');
--changeset mikhailRogov:7
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(9,1,'Vegan');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(10,1,'Vegeterian');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(11,1,'Does not matter');

INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(9,2,'Веган');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(10,2,'Вегетерианец');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(11,2,'Не имеет значения');
--changeset mikhailRogov:8
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(12,1,'I cook at home and take it with me');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(13,1,'Trying to cook at home if possible');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(14,1,'I cook very rarely, mostly I use food delivery');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(15,1,'Do no eat at home');

INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(12,2,'Готовлю дома и беру еду с собой');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(13,2,'Стараюсь готовить дома, если возможно');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(14,2,'Готовлю дома редко, заказываю еду домой');
INSERT INTO I_ANSWER_EXTENDED_LOCALE (`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(15,2,'Не питаюсь дома');
--changeset mikhailRogov:9
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(1,1,1,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(2,1,2,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(3,1,3,0);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(4,1,4,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(5,2,1,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(6,2,2,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(7,2,3,0);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(8,2,4,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(9,3,1,0);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(10,3,2,0);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(11,3,3,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(12,3,4,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(13,4,1,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(14,4,2,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(15,4,3,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(16,4,4,4);
--changeset mikhailRogov:10
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(17,5,5,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(18,5,6,0);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(19,5,7,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(20,5,8,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(21,6,5,0);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(22,6,6,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(23,6,7,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(24,6,8,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(25,7,5,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(26,7,6,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(27,7,7,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(28,7,8,3);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(29,8,5,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(30,8,6,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(31,8,7,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(32,8,8,4);
--changeset mikhailRogov:11
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(33,9,9,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(34,9,10,3);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(35,9,11,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(36,10,9,3);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(37,10,10,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(38,10,11,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(39,11,9,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(40,11,10,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(41,11,11,4);
--changeset mikhailRogov:12
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(42,12,12,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(43,12,13,3);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(44,12,14,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(45,12,15,1);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(46,13,12,3);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(47,13,13,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(48,13,14,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(49,13,15,1);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(50,14,12,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(51,14,13,3);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(52,14,14,4);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(53,14,15,1);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(54,15,12,1);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(55,15,13,2);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(56,15,14,3);
INSERT INTO ANSWER_SIMILARITY (`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(57,15,15,4);
--changeset mikhailRogov:13
INSERT INTO I_QUESTION_IMPORTANCE_LOCALE (`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (1,1,"Very important");
INSERT INTO I_QUESTION_IMPORTANCE_LOCALE (`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (1,2,"Somewhat important");
INSERT INTO I_QUESTION_IMPORTANCE_LOCALE (`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (1,3,"A little important");
INSERT INTO I_QUESTION_IMPORTANCE_LOCALE (`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (1,4,"Irrelevant");

INSERT INTO I_QUESTION_IMPORTANCE_LOCALE (`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (2,1,"Очень важно");
INSERT INTO I_QUESTION_IMPORTANCE_LOCALE (`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (2,2,"Достаточно важно");
INSERT INTO I_QUESTION_IMPORTANCE_LOCALE (`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (2,3,"Немного важно");
INSERT INTO I_QUESTION_IMPORTANCE_LOCALE (`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (2,4,"Не имеет значения");
