ALTER TABLE `USER_ACCOUNT`
DROP FOREIGN KEY `I_ACCOUNT_TYPES`,
DROP FOREIGN KEY `I_ACCOUNT_STATUSES`;
ALTER TABLE `USER_ACCOUNT`
DROP INDEX `I_ACCOUNT_TYPES_idx` ,
DROP INDEX `I_ACCOUNT_STATUSES_idx` ;

DROP TABLE`I_ACCOUNT_STATUS`, `I_ACCOUNT_TYPE`;