CREATE TABLE `I_CITY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COUNTRY_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CITY_COUNTRY_ID_COUNTRY`
    FOREIGN KEY (`COUNTRY_ID`)
    REFERENCES `I_COUNTRY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(1,1,"Akko");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(2,1,"Afula");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(3,1,"Arad");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(4,1,"Ariel");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(5,1,"Arraba");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(6,1,"Ashdod");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(7,1,"Ashkelond");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(8,1,"Baqa al-Gharbiyye");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(9,1,"Bat Yam");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(10,1,"Beersheba");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(11,1,"Beit She'an");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(12,1,"Beit Shemesh");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(13,1,"Beitar Illit");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(14,1,"Bnei Brak");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(15,1,"Dimona");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(16,1,"Eilat");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(17,1,"El'ad");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(18,1,"Giv'at Shmuel");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(19,1,"Givatayim");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(20,1,"Hadera");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(21,1,"Haifa");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(22,1,"Herzliya");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(23,1,"Hod HaSharon");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(24,1,"Holon");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(25,1,"Jerusalem");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(26,1,"Kafr Qasim");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(27,1,"Karmiel");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(28,1,"Kfar Saba");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(29,1,"Kfar Yona");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(30,1,"Kiryat Ata");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(31,1,"Kiryat Bialik");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(32,1,"Kiryat Gat");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(33,1,"Kiryat Malakhi");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(34,1,"Kiryat Motzkin");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(35,1,"Kiryat Ono");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(36,1,"Kiryat Shmona");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(37,1,"Kiryat Yam");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(38,1,"Lod");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(39,1,"Ma'ale Adumim");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(40,1,"Ma'alot-Tarshiha");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(41,1,"Migdal HaEmek");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(42,1,"Modi'in Illit");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(43,1,"Modi'in-Maccabim-Re'ut");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(44,1,"Nahariya");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(45,1,"Nazareth");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(46,1,"Nazareth Illit");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(47,1,"Nesher");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(48,1,"Ness Ziona");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(49,1,"Netanya");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(50,1,"Netivot");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(51,1,"Ofakim");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(52,1,"Or Akiva");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(53,1,"Or Yehuda");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(54,1,"Petah Tikva");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(55,1,"Qalansawe");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(56,1,"Ra'anana");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(57,1,"Rahat");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(58,1,"Ramat Gan");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(59,1,"Ramat HaSharon");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(60,1,"Ramla");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(61,1,"Rehovot");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(62,1,"Rishon LeZion");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(63,1,"Rosh HaAyin");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(64,1,"Safed");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(65,1,"Sakhnin");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(66,1,"Sderot");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(67,1,"Shefa-'Amr");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(68,1,"Tamra");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(69,1,"Tayibe");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(70,1,"Tel Aviv");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(71,1,"Tiberias");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(72,1,"Tira");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(73,1,"Tirat Carmel");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(74,1,"Umm al-Fahm");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(75,1,"Yavne");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(76,1,"Yehud");
INSERT INTO `i_city`(`ID`,`COUNTRY_ID`,`DESCRIPTION`)VALUES(77,1,"Yokneam");