CREATE TABLE `USER_IMAGE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT NULL,
  `LOCAL_PATH` VARCHAR(200) NULL,
  `IMAGE_STORAGE_ID` BIGINT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL,
  `UPDATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `LOCAL_PATH_UNIQUE` (`LOCAL_PATH` ASC),
  INDEX `FK_USER_IMAGE_USER_ID_USER_idx` (`USER_ID` ASC),
  CONSTRAINT `FK_USER_IMAGE_USER_ID_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

