CREATE TABLE `IMAGE_STORAGE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_IMAGE_ID` BIGINT NULL,
  `BASE_64_IMAGE` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_IMAGE_STORAGE_USER_IMAGE_ID_USER_IMAGE_idx` (`USER_IAMGE_ID` ASC),
  CONSTRAINT `FK_IMAGE_STORAGE_USER_IMAGE_ID_USER_IMAGE`
    FOREIGN KEY (`USER_IAMGE_ID`)
    REFERENCES `USER_IMAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



