ALTER TABLE `USER_IMAGE`
ADD INDEX `FK_USER_IMAGE_IMAGE_STORAGE_ID_IMAGE_STORAGE_idx` (`IMAGE_STORAGE_ID` ASC);
ALTER TABLE `USER_IMAGE`
ADD CONSTRAINT `FK_USER_IMAGE_IMAGE_STORAGE_ID_IMAGE_STORAGE`
  FOREIGN KEY (`IMAGE_STORAGE_ID`)
  REFERENCES `IMAGE_STORAGE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;