CREATE TABLE `I_GENDER_LOCALE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `GENDER_ID` INT NOT NULL,
  `LANGUAGE_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC),
  CONSTRAINT `FK_GENDER_LOCALE_LANGUAGE_ID_LANGUAGE`
    FOREIGN KEY (`LANGUAGE_ID`)
    REFERENCES `I_LANGUAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GENDER_LOCALE_GENDER_ID_GENDER`
    FOREIGN KEY (`GENDER_ID`)
    REFERENCES `I_GENDER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `i_gender_locale`(`ID`,`GENDER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(1,1,1,'Male');
INSERT INTO `i_gender_locale`(`ID`,`GENDER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(2,2,1,'Female');
INSERT INTO `i_gender_locale`(`ID`,`GENDER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(3,3,1,'Other');
INSERT INTO `i_gender_locale`(`ID`,`GENDER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(4,1,2,'Мужской');
INSERT INTO `i_gender_locale`(`ID`,`GENDER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(5,2,2,'Женский');
INSERT INTO `i_gender_locale`(`ID`,`GENDER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(6,3,2,'Другой');