ALTER TABLE `userdb`.`user_account`
ADD COLUMN `USER_IMAGE_ID` BIGINT(20) NULL AFTER `LANGUAGE_ID`;
ALTER TABLE `userdb`.`user_account`
ADD CONSTRAINT `FK_USER_ACCOUNT_USER_IMAGE_ID_USER_IMAGE_ID`
  FOREIGN KEY (`USER_IMAGE_ID`)
  REFERENCES `userdb`.`user_image` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;