CREATE TABLE `I_COUNTRY_LOCALE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COUNTRY_ID` INT NOT NULL,
  `LANGUAGE_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC),
  CONSTRAINT `FK_COUNTRY_LOCALE_LANGUAGE_ID_LANGUAGE`
    FOREIGN KEY (`LANGUAGE_ID`)
    REFERENCES `I_LANGUAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COUNTRY_LOCALE_COUNTRY_ID_COUNTRY`
    FOREIGN KEY (`COUNTRY_ID`)
    REFERENCES `I_COUNTRY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `i_country_locale`(`ID`,`COUNTRY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(1,1,1,'Israel');
INSERT INTO `i_country_locale`(`ID`,`COUNTRY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(2,1,2,'Израиль');