ALTER TABLE `USER_LOGIN_LOG`
DROP FOREIGN KEY FK_USER_LOGIN_LOG_USER_ID_USER;
ALTER TABLE `USER_LOGIN_LOG`
DROP INDEX USER_ID_UNIQUE;
ALTER TABLE `USER_LOGIN_LOG`
ADD INDEX FK_USER_LOGIN_LOG_USER_ID_USER_idx (`USER_ID` ASC),
ALTER COLUMN IS_LOGIN_SUCCESS SET DEFAULT 0;
ALTER TABLE `USER_LOGIN_LOG`
ADD CONSTRAINT `FK_USER_LOGIN_LOG_USER_ID_USER`
  FOREIGN KEY (`USER_ID`)
  REFERENCES `USER` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

