ALTER TABLE userdb.user_login_log DROP FOREIGN KEY FK_USER_LOGIN_LOG_USER_ID_USER;
DROP INDEX USER_ID_UNIQUE ON userdb.user_login_log;
ALTER TABLE `USER_LOGIN_LOG`
ADD INDEX `FK_USER_LOGIN_LOG_USER_ID_USER_idx` (`USER_ID` ASC);
ALTER TABLE `USER_LOGIN_LOG`
ADD CONSTRAINT `FK_USER_LOGIN_LOG_USER_ID_USER`
  FOREIGN KEY (`USER_ID`)
  REFERENCES `USER` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


