CREATE TABLE `USER_INFO` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT NOT NULL,
  `CURRENT_CITY_ID` INT NULL,
  `GENDER_ID` INT NULL,
  `FACEBOOK_LINK` VARCHAR(255) NULL,
  `PROFESSION` VARCHAR(255) NULL,
  `COMPANY` VARCHAR(255) NULL,
  `PHONE_NUMBER` VARCHAR(20) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC),
  CONSTRAINT `FK_USER_INFO_USER_ID_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `userdb`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_INFO_CURRENT_CITY_ID_I_CITY`
    FOREIGN KEY (`CURRENT_CITY_ID`)
    REFERENCES `userdb`.`i_city` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_INFO_GENDER_ID_I_GENDER`
    FOREIGN KEY (`GENDER_ID`)
    REFERENCES `userdb`.`i_gender` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
