CREATE TABLE `USER_MANDATORY_MATCH_RESULT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT NOT NULL,
  `USER_MATCH_EXPRESSION` TEXT,
  `MATCH_REGEX` TEXT,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC),
  CONSTRAINT `FK_USER_MANDATORY_MATCH_RESULT_USER_ID_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
