CREATE TABLE `I_QUESTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IS_ACTIVE` BIT NULL DEFAULT 1,
  `IS_MUST` BIT NULL DEFAULT 1,
  PRIMARY KEY (`ID`));

INSERT INTO `i_question` (`ID`,`IS_ACTIVE`,`IS_MUST`) VALUES(1,TRUE ,TRUE );
INSERT INTO `i_question` (`ID`,`IS_ACTIVE`,`IS_MUST`) VALUES(2,TRUE ,TRUE );
INSERT INTO `i_question` (`ID`,`IS_ACTIVE`,`IS_MUST`) VALUES(3,TRUE ,TRUE );
INSERT INTO `i_question` (`ID`,`IS_ACTIVE`,`IS_MUST`) VALUES(4,TRUE ,TRUE );
INSERT INTO `i_question` (`ID`,`IS_ACTIVE`,`IS_MUST`) VALUES(5,TRUE ,TRUE );
