CREATE TABLE `CHAT_MESSAGE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CHAT_ID` BIGINT NOT NULL,
  `USER_ID` BIGINT NOT NULL,
  `MESSAGE` LONGTEXT NOT NULL,
  `MESSAGE_TYPE_ID` INT NOT NULL,
  `PERMITED_USERS` VARCHAR(200),
  `CREATED_DATE` TIMESTAMP NOT NULL,
  `UPDATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_CHAT_MESSAGE_CHAT_ID_CHAT_idx` (`CHAT_ID` ASC),
  INDEX `FK_CHAT_MESSAGE_USER_ID_USER_idx` (`USER_ID` ASC),
  CONSTRAINT `FK_CHAT_MESSAGE_CHAT_ID_CHAT`
    FOREIGN KEY (`CHAT_ID`)
    REFERENCES `CHAT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CHAT_MESSAGE_USER_ID_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);