CREATE TABLE `I_ACCOUNT_STATUS` (
  `ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC));

INSERT INTO `I_ACCOUNT_STATUS`(`ID`, `DESCRIPTION`) VALUES (1,"NEW");
INSERT INTO `I_ACCOUNT_STATUS`(`ID`, `DESCRIPTION`) VALUES (2,"CONFIRMED");
INSERT INTO `I_ACCOUNT_STATUS`(`ID`, `DESCRIPTION`) VALUES (3,"BLOCKED");
