CREATE TABLE `I_QUESTION_LOCALE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QUESTION_ID` INT NOT NULL,
  `LANGUAGE_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC),
  CONSTRAINT `FK_QUESTION_LOCALE_LANGUAGE_ID_LANGUAGE`
    FOREIGN KEY (`LANGUAGE_ID`)
    REFERENCES `I_LANGUAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_QUESTION_LOCALE_QUESTION_ID_QUESTION`
    FOREIGN KEY (`QUESTION_ID`)
    REFERENCES `I_QUESTION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(1,1,1,'I''m looking for');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(2,2,1,'Pets');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(3,3,1,'Attitude to pets');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(4,4,1,'Neighbor gender');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(5,5,1,'Number of neighbors');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(6,6,1,'Age');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(7,7,1,'Payment limits');

INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(8,1,2,'я ищу');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(9,2,2,'Домашние животные');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(10,3,2,'Отножение к домашним животным');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(11,4,2,'Предпочтительный пол');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(12,5,2,'Количество соседей');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(13,6,2,'Возраст');
INSERT INTO `i_question_locale`(`ID`,`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(14,7,2,'Мой денежный лимит в месяц');
