CREATE TABLE `I_ANSWER_LOCALE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ANSWER_ID` INT NOT NULL,
  `LANGUAGE_ID` INT NOT NULL,
  `QUESTION_ID` BIGINT NOT NULL,
  `DESCRIPTION` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
--  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC),
  INDEX `FK_ANSWER_LOCALE_QUESTION_ID_QUESTION_idx` (`QUESTION_ID` ASC),
  CONSTRAINT `FK_ANSWER_LOCALE_LANGUAGE_ID_LANGUAGE`
    FOREIGN KEY (`LANGUAGE_ID`)
    REFERENCES `I_LANGUAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ANSWER_LOCALE_ANSWER_ID_ANSWER`
    FOREIGN KEY (`ANSWER_ID`)
    REFERENCES `I_ANSWER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(1,1,1,1,'A neighbor for what would have sat down in his apartment');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(2,2,1,1,'Neighbor to look for a new apartment together');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(3,3,1,1,'I want to find a free room to enter');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(4,4,1,2,'I have');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(5,5,1,2,'I do not have');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(6,6,1,3,'Unacceptable');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(7,7,1,3,'There are no problems if the owner follows him');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(8,8,1,4,'Man');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(9,9,1,4,'Women');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(10,10,1,4,'It does not matter to me');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(11,11,1,5,'1');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(12,12,1,5,'2');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(13,13,1,5,'3');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(14,14,1,5,'4');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(15,10,1,4,'It does not matter to me');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(16,15,1,6,'18-22');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(17,16,1,6,'23-27');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(18,17,1,6,'28-34');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(19,18,1,6,'35-41');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(20,10,1,6,'It does not matter to me');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(21,19,1,7,'1500-2000');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(22,20,1,7,'2000-2500');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(23,21,1,7,'2500-3000');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(24,22,1,7,'3000-3500');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(25,23,1,7,'3500-4000');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(26,10,1,7,'It does not matter to me');


INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(27,1,2,1,'Соседа для того что бы подселись к себе в квартиру');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(28,2,2,1,'Соседа что-бы вместе искать новую квартиру');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(29,3,2,1,'Хочу найти свободную комнату что бы въехать');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(30,4,2,2,'Есть');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(31,5,2,2,'Нет');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(32,6,2,3,'Непреемлемо');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(33,7,2,3,'Нет ни каких проблем, если хозяин за ним следит');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(34,8,2,4,'М.');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(35,9,2,4,'Ж.');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(36,10,2,4,'Неважо');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(37,11,2,5,'1');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(38,12,2,5,'2');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(39,13,2,5,'3');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(40,14,2,5,'4');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(41,10,2,4,'Неважо');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(42,15,2,6,'18-22');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(43,16,2,6,'23-27');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(44,17,2,6,'28-34');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(45,18,2,6,'35-41');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(46,10,2,6,'Неважо');

INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(47,19,2,7,'1500-2000');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(48,20,2,7,'2000-2500');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(49,21,2,7,'2500-3000');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(50,22,2,7,'3000-3500');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(51,23,2,7,'3500-4000');
INSERT INTO `i_answer_locale`(`ID`,`ANSWER_ID`,`LANGUAGE_ID`,`QUESTION_ID`,`DESCRIPTION`)VALUES(52,10,2,7,'Неважо');
