CREATE TABLE `I_ANSWER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ANSWER_ID` INT NOT NULL,
  `IS_UNIVERSAL` BIT NULL DEFAULT 0,
  `QUESTION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_ANSWER_QUESTION_ID_QUESTION_idx` (`QUESTION_ID` ASC));

INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(1,FALSE,1);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(2,FALSE,1);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(3,FALSE,1);

INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(4,FALSE,2);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(5,FALSE,2);

INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(6,FALSE,3);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(7,FALSE,3);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(8,FALSE,3);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(9,FALSE,3);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(10,TRUE,3);

INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(11,FALSE,4);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(12,FALSE,4);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(13,FALSE,4);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(14,FALSE,4);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(15,FALSE,4);
INSERT INTO `I_ANSWER` (`ANSWER_ID`,`IS_UNIVERSAL`,`QUESTION_ID`) VALUES(16,TRUE,4);