CREATE TABLE `I_QUESTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IS_ACTIVE` BIT NULL DEFAULT 1,
  `QUESTION_TYPE` TINYINT DEFAULT 1,
  PRIMARY KEY (`ID`));

INSERT INTO `I_QUESTION` (`ID`,`IS_ACTIVE`,`QUESTION_TYPE`) VALUES(1,TRUE,1);
INSERT INTO `I_QUESTION` (`ID`,`IS_ACTIVE`,`QUESTION_TYPE`) VALUES(2,TRUE,1);
INSERT INTO `I_QUESTION` (`ID`,`IS_ACTIVE`,`QUESTION_TYPE`) VALUES(3,TRUE,1);
INSERT INTO `I_QUESTION` (`ID`,`IS_ACTIVE`,`QUESTION_TYPE`) VALUES(4,TRUE,1);
INSERT INTO `I_QUESTION` (`ID`,`IS_ACTIVE`,`QUESTION_TYPE`) VALUES(5,TRUE,3);
INSERT INTO `I_QUESTION` (`ID`,`IS_ACTIVE`,`QUESTION_TYPE`) VALUES(6,TRUE,2);