CREATE TABLE `USER_MANDATORY_MATCH_RESULT` (
  `USER_ID` BIGINT(20) NOT NULL,
  `QUESTION_ID` INT(11) NOT NULL,
  `ANSWER_ID` INT(11) NOT NULL,
  UNIQUE KEY `USER_ID_UNIQUE` (`USER_ID`),
  UNIQUE KEY `QUESTION_ID_UNIQUE` (`QUESTION_ID`),
  UNIQUE KEY `ANSWER_ID_UNIQUE` (`ANSWER_ID`)
);