CREATE TABLE `USER_QUESTION_ANSWER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT(20) NOT NULL,
  `QUESTION_ID` INT(11) NOT NULL,
  `ANSWER_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`)
);

INSERT INTO `USER_QUESTION_ANSWER` (`USER_ID`, `QUESTION_ID`, `ANSWER_ID`)
VALUES (1,1,3);
INSERT INTO `USER_QUESTION_ANSWER` (`USER_ID`, `QUESTION_ID`, `ANSWER_ID`)
VALUES (1,2,4);
INSERT INTO `USER_QUESTION_ANSWER` (`USER_ID`, `QUESTION_ID`, `ANSWER_ID`)
VALUES (1,3,6);
INSERT INTO `USER_QUESTION_ANSWER` (`USER_ID`, `QUESTION_ID`, `ANSWER_ID`)
VALUES (1,4,14);


INSERT INTO `USER_QUESTION_ANSWER` (`USER_ID`, `QUESTION_ID`, `ANSWER_ID`)
VALUES (2,1,3);
INSERT INTO `USER_QUESTION_ANSWER` (`USER_ID`, `QUESTION_ID`, `ANSWER_ID`)
VALUES (2,2,4);
INSERT INTO `USER_QUESTION_ANSWER` (`USER_ID`, `QUESTION_ID`, `ANSWER_ID`)
VALUES (2,3,10);
INSERT INTO `USER_QUESTION_ANSWER` (`USER_ID`, `QUESTION_ID`, `ANSWER_ID`)
VALUES (2,4,14);
