CREATE TABLE `ANSWER_SIMILARITY` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `ANSWER_ID` INT NOT NULL,
  `ANSWER_TO_COMPARE_ID` INT NOT NULL,
  `SIMILARITY_SCORE` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_ANSWER_SIMILARITY_ANSWER_TO_COMPARE_ID_ANSWER_idx` (`ANSWER_TO_COMPARE_ID` ASC),
  INDEX `FK_ANSWER_SIMILARITY_ANSWER_ID_ANSWER_idx` (`ANSWER_ID` ASC),
  CONSTRAINT `FK_ANSWER_SIMILARITY_ANSWER_ID_ANSWER`
    FOREIGN KEY (`ANSWER_ID`)
    REFERENCES `userdb`.`i_answer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ANSWER_SIMILARITY_ANSWER_TO_COMPARE_ID_ANSWER`
    FOREIGN KEY (`ANSWER_TO_COMPARE_ID`)
    REFERENCES `userdb`.`i_answer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);