ALTER TABLE `USER_QUESTION_ANSWER`
ADD COLUMN `QUESTION_IMPORTANCE_ID` INT NULL AFTER `ANSWER_ID`,
ADD INDEX `FK_USER_QUESTION_ANSWER_QUESTION_IMPORTANCE_ID_QUESTION_IMP_idx` (`QUESTION_IMPORTANCE_ID` ASC);
ALTER TABLE `userdb`.`user_question_answer`
ADD CONSTRAINT `FK_USER_QUESTION_ANSWER_QUESTION_IMPORTANCE`
  FOREIGN KEY (`QUESTION_IMPORTANCE_ID`)
  REFERENCES `userdb`.`question_importance` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;