CREATE TABLE `I_QUESTION_IMPORTANCE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `WEIGHT` INT NOT NULL,
  PRIMARY KEY (`ID`));

INSERT INTO `I_QUESTION_IMPORTANCE`(`ID`,`WEIGHT`) VALUES (1,100);
INSERT INTO `I_QUESTION_IMPORTANCE`(`ID`,`WEIGHT`) VALUES (2,10);
INSERT INTO `I_QUESTION_IMPORTANCE`(`ID`,`WEIGHT`) VALUES (3,1);
INSERT INTO `I_QUESTION_IMPORTANCE`(`ID`,`WEIGHT`) VALUES (4,0);