INSERT INTO `I_QUESTION_LOCALE`(`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(5,1,'City');
INSERT INTO `I_QUESTION_LOCALE`(`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(6,1,'Gender of potential neighbor');

INSERT INTO `I_QUESTION_LOCALE`(`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(5,2,'Город');
INSERT INTO `I_QUESTION_LOCALE`(`QUESTION_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(6,2,'Пол потенциального соседа');