CREATE TABLE `I_LANGUAGE` (
  `ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  `LANGUAGE_NATIVE_NAME` VARCHAR(100) NOT NULL,
  `IS_ACTIVE` BIT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC));

INSERT INTO `I_LANGUAGE`(`ID`, `DESCRIPTION`, `LANGUAGE_NATIVE_NAME`, `IS_ACTIVE`) VALUES (1,"en","English",TRUE);
INSERT INTO `I_LANGUAGE`(`ID`, `DESCRIPTION`, `LANGUAGE_NATIVE_NAME`, `IS_ACTIVE`) VALUES (2,"ru","Русский",TRUE);