CREATE TABLE `I_LANGUAGE` (
  `ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  `LANGUAGE_NATIVE_NAME` VARCHAR(100) NOT NULL,
  `IS_ACTIVE` BIT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC));