CREATE TABLE `I_QUESTION_EXTENDED` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`));

INSERT INTO `I_QUESTION_EXTENDED` (`ID`) VALUES(1);
INSERT INTO `I_QUESTION_EXTENDED` (`ID`) VALUES(2);
INSERT INTO `I_QUESTION_EXTENDED` (`ID`) VALUES(3);
INSERT INTO `I_QUESTION_EXTENDED` (`ID`) VALUES(4);