CREATE TABLE `ANSWER_SIMILARITY` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `ANSWER_ID` INT NOT NULL,
  `ANSWER_TO_COMPARE_ID` INT NOT NULL,
  `SIMILARITY_SCORE` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_ANSWER_SIMILARITY_ANSWER_TO_COMPARE_ID_ANSWER_idx` (`ANSWER_TO_COMPARE_ID` ASC),
  INDEX `FK_ANSWER_SIMILARITY_ANSWER_ID_ANSWER_idx` (`ANSWER_ID` ASC),
  CONSTRAINT `FK_ANSWER_SIMILARITY_ANSWER_ID_ANSWER_EXTENDED`
    FOREIGN KEY (`ANSWER_ID`)
    REFERENCES `I_ANSWER_EXTENDED` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ANSWER_SIMILARITY_ANSWER_TO_COMPARE_ID_ANSWER`
    FOREIGN KEY (`ANSWER_TO_COMPARE_ID`)
    REFERENCES `I_ANSWER_EXTENDED` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(1,1,1,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(2,1,2,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(3,1,3,0);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(4,1,4,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(5,2,1,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(6,2,2,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(7,2,3,0);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(8,2,4,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(9,3,1,0);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(10,3,2,0);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(11,3,3,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(12,3,4,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(13,4,1,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(14,4,2,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(15,4,3,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(16,4,4,4);

INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(17,5,5,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(18,5,6,0);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(19,5,7,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(20,5,8,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(21,6,5,0);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(22,6,6,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(23,6,7,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(24,6,8,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(25,7,5,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(26,7,6,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(27,7,7,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(28,7,8,3);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(29,8,5,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(30,8,6,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(31,8,7,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(32,8,8,4);

INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(33,9,9,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(34,9,10,3);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(35,9,11,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(36,10,9,3);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(37,10,10,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(38,10,11,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(39,11,9,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(40,11,10,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(41,11,11,4);

INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(42,12,12,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(43,12,13,3);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(44,12,14,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(45,12,15,1);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(46,13,12,3);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(47,13,13,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(48,13,14,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(49,13,15,1);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(50,14,12,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(51,14,13,3);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(52,14,14,4);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(53,14,15,1);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(54,15,12,1);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(55,15,13,2);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(56,15,14,3);
INSERT INTO `ANSWER_SIMILARITY`(`ID`,`ANSWER_ID`,`ANSWER_TO_COMPARE_ID`,`SIMILARITY_SCORE`) VALUES(57,15,15,4);