CREATE TABLE `USER_ACCOUNT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT NOT NULL,
  `ACCOUNT_STATUS_ID` INT NOT NULL,
  `ACCOUNT_TYPE_ID` INT NOT NULL,
  `LANGUAGE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC),
  INDEX `I_ACCOUNT_STATUSES_idx` (`ACCOUNT_STATUS_ID` ASC),
  INDEX `I_ACCOUNT_TYPES_idx` (`ACCOUNT_TYPE_ID` ASC),
  INDEX `I_LANGUAGE_idx` (`LANGUAGE_ID` ASC),
  CONSTRAINT `FK_USER_ACCOUNT_USER_ID_USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `I_ACCOUNT_STATUSES`
    FOREIGN KEY (`ACCOUNT_STATUS_ID`)
    REFERENCES `I_ACCOUNT_STATUS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `I_ACCOUNT_TYPES`
    FOREIGN KEY (`ACCOUNT_TYPE_ID`)
    REFERENCES `I_ACCOUNT_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `I_LANGUAGE`
    FOREIGN KEY (`LANGUAGE_ID`)
    REFERENCES `I_LANGUAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
