CREATE TABLE `I_GENDER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LANGUAGE_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC),
  CONSTRAINT `FK_GENDER_LANGUAGE_ID_LANGUAGE`
    FOREIGN KEY (`LANGUAGE_ID`)
    REFERENCES `I_LANGUAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `i_gender` (`ID`,`LANGUAGE_ID`,`DESCRIPTION`) VALUES(1,1,'male');
INSERT INTO `i_gender` (`ID`,`LANGUAGE_ID`,`DESCRIPTION`) VALUES(2,1,'female');
INSERT INTO `i_gender` (`ID`,`LANGUAGE_ID`,`DESCRIPTION`) VALUES(3,1,'other');
INSERT INTO `i_gender` (`ID`,`LANGUAGE_ID`,`DESCRIPTION`) VALUES(4,2,'мужской');
INSERT INTO `i_gender` (`ID`,`LANGUAGE_ID`,`DESCRIPTION`) VALUES(5,2,'женский');
INSERT INTO `i_gender` (`ID`,`LANGUAGE_ID`,`DESCRIPTION`) VALUES(6,2,'другой');