CREATE TABLE `I_GENDER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC));

INSERT INTO `i_gender` (`ID`, `DESCRIPTION`) VALUES(1, 'male');
INSERT INTO `i_gender` (`ID`, `DESCRIPTION`) VALUES(2, 'female');
INSERT INTO `i_gender` (`ID`, `DESCRIPTION`) VALUES(3, 'other');
