ALTER TABLE `EMAIL_NOTIFICATION_LOG` 
CHANGE COLUMN `EMAIL_CONTENT_JSON` `EMAIL_CONTENT` LONGTEXT NULL ,
ADD INDEX `FK_EMAIL_NOTIFICATION_LOG_USER_ID_USER_idx` (`USER_ID` ASC);
ALTER TABLE `EMAIL_NOTIFICATION_LOG`
ADD CONSTRAINT `FK_EMAIL_NOTIFICATION_LOG_USER_ID_USER`
  FOREIGN KEY (`USER_ID`)
  REFERENCES `USER` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
