CREATE TABLE `REGISTRATION_CONFIRMATION` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT NOT NULL,
  `URL_LINK` VARCHAR(50) NOT NULL,
  `IS_CONFIRMED` BIT NOT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL,
  `UPDATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_REGISTRATION_CONFIRMATION_USER_ID_USER_idx` (`USER_ID` ASC),
  CONSTRAINT `FK_REGISTRATION_CONFIRMATION_USER_ID_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
