CREATE TABLE `I_GENDER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`));

INSERT INTO `I_GENDER` (`ID`) VALUES(1);
INSERT INTO `I_GENDER` (`ID`) VALUES(2);
INSERT INTO `I_GENDER` (`ID`) VALUES(3);
