CREATE TABLE `I_CITY_LOCALE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CITY_ID` INT NOT NULL,
  `LANGUAGE_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CITY_LOCALE_LANGUAGE_ID_LANGUAGE`
    FOREIGN KEY (`LANGUAGE_ID`)
    REFERENCES `I_LANGUAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CITY_LOCALE_CITY_ID_CITY`
    FOREIGN KEY (`CITY_ID`)
    REFERENCES `I_CITY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(1,1,1,"Akko");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(2,2,1,"Afula");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(3,3,1,"Arad");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(4,4,1,"Ariel");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(5,5,1,"Arraba");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(6,6,1,"Ashdod");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(7,7,1,"Ashkelond");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(8,8,1,"Baqa al-Gharbiyye");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(9,9,1,"Bat Yam");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(10,10,1,"Beersheba");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(11,11,1,"Beit She'an");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(12,12,1,"Beit Shemesh");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(13,13,1,"Beitar Illit");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(14,14,1,"Bnei Brak");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(15,15,1,"Dimona");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(16,16,1,"Eilat");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(17,17,1,"El'ad");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(18,18,1,"Giv'at Shmuel");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(19,19,1,"Givatayim");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(20,20,1,"Hadera");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(21,21,1,"Haifa");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(22,22,1,"Herzliya");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(23,23,1,"Hod HaSharon");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(24,24,1,"Holon");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(25,25,1,"Jerusalem");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(26,26,1,"Kafr Qasim");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(27,27,1,"Karmiel");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(28,28,1,"Kfar Saba");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(29,29,1,"Kfar Yona");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(30,30,1,"Kiryat Ata");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(31,31,1,"Kiryat Bialik");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(32,32,1,"Kiryat Gat");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(33,33,1,"Kiryat Malakhi");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(34,34,1,"Kiryat Motzkin");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(35,35,1,"Kiryat Ono");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(36,36,1,"Kiryat Shmona");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(37,37,1,"Kiryat Yam");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(38,38,1,"Lod");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(39,39,1,"Ma'ale Adumim");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(40,40,1,"Ma'alot-Tarshiha");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(41,41,1,"Migdal HaEmek");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(42,42,1,"Modi'in Illit");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(43,43,1,"Modi'in-Maccabim-Re'ut");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(44,44,1,"Nahariya");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(45,45,1,"Nazareth");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(46,46,1,"Nazareth Illit");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(47,47,1,"Nesher");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(48,48,1,"Ness Ziona");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(49,49,1,"Netanya");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(50,50,1,"Netivot");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(51,51,1,"Ofakim");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(52,52,1,"Or Akiva");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(53,53,1,"Or Yehuda");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(54,54,1,"Petah Tikva");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(55,55,1,"Qalansawe");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(56,56,1,"Ra'anana");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(57,57,1,"Rahat");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(58,58,1,"Ramat Gan");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(59,59,1,"Ramat HaSharon");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(60,60,1,"Ramla");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(61,61,1,"Rehovot");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(62,62,1,"Rishon LeZion");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(63,63,1,"Rosh HaAyin");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(64,64,1,"Safed");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(65,65,1,"Sakhnin");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(66,66,1,"Sderot");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(67,67,1,"Shefa-'Amr");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(68,68,1,"Tamra");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(69,69,1,"Tayibe");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(70,70,1,"Tel Aviv");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(71,71,1,"Tiberias");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(72,72,1,"Tira");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(73,73,1,"Tirat Carmel");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(74,74,1,"Umm al-Fahm");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(75,75,1,"Yavne");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(76,76,1,"Yehud");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(77,77,1,"Yokneam");

INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(78,1,2,"Акко");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(79,2,2,"Афула");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(80,3,2,"Арад");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(81,4,2,"Ариэль");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(82,5,2,"Арраба");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(83,6,2,"Ашдод");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(84,7,2,"Ашкелон");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(85,8,2,"Бака-аль-Гарбия");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(86,9,2,"Бат-Ям");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(87,10,2,"Беэр-Шева");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(88,11,2,"Бейт-Шеан");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(89,12,2,"Бейт-Шемеш");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(90,13,2,"Бейтар-Илит");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(91,14,2,"Бней-Брак");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(92,15,2,"Димона");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(93,16,2,"Эйлат");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(94,17,2,"Эльад");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(95,18,2,"Гиват-Шмуэль");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(96,19,2,"Гиватаим");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(97,20,2,"Хадера");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(98,21,2,"Хайфа");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(99,22,2,"Герцлия");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(100,23,2,"Ход-ха-Шарон");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(101,24,2,"Холон");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(102,25,2,"Иерусалим");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(103,26,2,"Кафр-Касем");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(104,27,2,"Кармиэль");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(105,28,2,"Кфар-Сава");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(106,29,2,"Кфар-Йона");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(107,30,2,"Кирьят-Ата");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(108,31,2,"Кирьят-Бялик");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(109,32,2,"Кирьят-Гат");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(110,33,2,"Кирьят-Малахи");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(111,34,2,"Кирьят-Моцкин");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(112,35,2,"Кирьят-Оно");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(113,36,2,"Кирьят-Шмона");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(114,37,2,"Кирьят-Ям");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(115,38,2,"Лод");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(116,39,2,"Маале-Адумим");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(117,40,2,"Маалот-Таршиха");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(118,41,2,"Мигдаль-ха-Эмек");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(119,42,2,"Модиин-Илит");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(120,43,2,"Модиин-Маккабим-Реут");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(121,44,2,"Нагария");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(122,45,2,"Назарет");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(123,46,2,"Нацрат-Иллит");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(124,47,2,"Нешер");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(125,48,2,"Нес-Циона");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(126,49,2,"Нетания");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(127,50,2,"Нетивот");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(128,51,2,"Офаким");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(129,52,2,"Ор-Акива");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(130,53,2,"Ор-Йехуда");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(131,54,2,"Петах-Тиква");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(132,55,2,"Калансуа");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(133,56,2,"Раанана");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(134,57,2,"Рахат");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(135,58,2,"Рамат-Ган");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(136,59,2,"Рамат-ха-Шарон");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(137,60,2,"Рамла");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(138,61,2,"Реховот");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(139,62,2,"Ришон-ле-Цион");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(140,63,2,"Рош-ха-Аин");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(141,64,2,"Сафед");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(142,65,2,"Сахнин");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(143,66,2,"Сдерот");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(144,67,2,"Шефарам");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(145,68,2,"Тамра");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(146,69,2,"Тайбе");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(147,70,2,"Тель-Авив");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(148,71,2,"Тверия");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(149,72,2,"Тира");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(150,73,2,"Тират-Кармель");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(151,74,2,"Умм-эль-Фахм");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(152,75,2,"Явне");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(153,76,2,"Йехуд");
INSERT INTO `i_city_locale`(`ID`,`CITY_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(154,77,2,"Йокнеам");