ALTER TABLE `USER_ACCOUNT`
ADD COLUMN `USER_IMAGE_ID` BIGINT(20) NULL AFTER `LANGUAGE_ID`;
ALTER TABLE `USER_ACCOUNT`
ADD CONSTRAINT `FK_USER_ACCOUNT_USER_IMAGE_ID_USER_IMAGE_ID`
  FOREIGN KEY (`USER_IMAGE_ID`)
  REFERENCES `USER_IMAGE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;