CREATE TABLE `I_ACCOUNT_TYPE` (
  `ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC));

INSERT INTO `I_ACCOUNT_TYPE`(`ID`, `DESCRIPTION`) VALUES (1,"REGULAR");