CREATE TABLE `IMAGE_PAIR` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `ORIGINAL_IMAGE_ID` BIGINT NOT NULL,
  `COMPRESSED_IMAGE_ID` BIGINT NOT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL,
  `UPDATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ORIGINAL_IMAGE_ID_UNIQUE` (`ORIGINAL_IMAGE_ID` ASC),
  UNIQUE INDEX `COMPRESSED_IMAGE_ID_UNIQUE` (`COMPRESSED_IMAGE_ID` ASC),
  CONSTRAINT `FK_IMAGE_PAIR_ORIGINAL_IMAGE_ID_USER_IMAGE_ID`
    FOREIGN KEY (`ORIGINAL_IMAGE_ID`)
    REFERENCES `USER_IMAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_IMAGE_PAIR_COMPRESSED_IMAGE_ID_USER_IMAGE_ID`
    FOREIGN KEY (`COMPRESSED_IMAGE_ID`)
    REFERENCES `USER_IMAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);