CREATE TABLE `I_ANSWER_EXTENDED_LOCALE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ANSWER_ID` INT NOT NULL,
  `LANGUAGE_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ANSWER_EXTENDED_LOCALE_LANGUAGE_ID_LANGUAGE`
    FOREIGN KEY (`LANGUAGE_ID`)
    REFERENCES `I_LANGUAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ANSWER_EXTENDED_LOCALE_ANSWER_ID_ANSWER_EXTENDED`
    FOREIGN KEY (`ANSWER_ID`)
    REFERENCES `I_ANSWER_EXTENDED` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(1,1,'Judaism');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(2,1,'Christianity');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(3,1,'Islam');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(4,1,'Ateism');

INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(1,2,'Иудаизм');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(2,2,'Христианство');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(3,2,'Ислам');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(4,2,'Атеизм');


INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(5,1,'Left');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(6,1,'Right');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(7,1,'Trying to find golden mean');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(8,1,'Does not matter');

INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(5,2,'Левые');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(6,2,'Правые');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(7,2,'Пытаюсь найти золотую середину');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(8,2,'Не имеет значение');


INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(9,1,'Vegan');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(10,1,'Vegeterian');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(11,1,'Does not matter');

INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(9,2,'Веган');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(10,2,'Вегетерианец');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(11,2,'Не имеет значения');


INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(12,1,'I cook at home and take it with me');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(13,1,'Trying to cook at home if possible');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(14,1,'I cook very rarely, mostly I use food delivery');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(15,1,'Do no eat at home');

INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(12,2,'Готовлю дома и беру еду с собой');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(13,2,'Стараюсь готовить дома, если возможно');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(14,2,'Готовлю дома редко, заказываю еду домой');
INSERT INTO `I_ANSWER_EXTENDED_LOCALE`(`ANSWER_ID`,`LANGUAGE_ID`,`DESCRIPTION`)VALUES(15,2,'Не питаюсь дома');