CREATE TABLE `I_QUESTION_IMPORTANCE_LOCALE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QUESTION_IMPORTANCE_ID` INT NOT NULL,
  `LANGUAGE_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRIPTION_UNIQUE` (`DESCRIPTION` ASC),
  CONSTRAINT `FK_QUESTION_IMPORTANCE_LOCALE_LANGUAGE_ID_LANGUAGE`
    FOREIGN KEY (`LANGUAGE_ID`)
    REFERENCES `I_LANGUAGE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_QUESTION_IMPORTANCE_LOCALE_QUESTION_IMPORTANCE_ID_QUESTION`
    FOREIGN KEY (`QUESTION_IMPORTANCE_ID`)
    REFERENCES `I_QUESTION_IMPORTANCE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `I_QUESTION_IMPORTANCE_LOCALE`(`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (1,1,"Very important");
INSERT INTO `I_QUESTION_IMPORTANCE_LOCALE`(`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (1,2,"Somewhat important");
INSERT INTO `I_QUESTION_IMPORTANCE_LOCALE`(`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (1,3,"A little important");
INSERT INTO `I_QUESTION_IMPORTANCE_LOCALE`(`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (1,4,"Irrelevant");

INSERT INTO `I_QUESTION_IMPORTANCE_LOCALE`(`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (2,1,"Очень важно");
INSERT INTO `I_QUESTION_IMPORTANCE_LOCALE`(`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (2,2,"Достаточно важно");
INSERT INTO `I_QUESTION_IMPORTANCE_LOCALE`(`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (2,3,"Немного важно");
INSERT INTO `I_QUESTION_IMPORTANCE_LOCALE`(`LANGUAGE_ID`,`QUESTION_IMPORTANCE_ID`,`DESCRIPTION`) VALUES (2,4,"Не имеет значения");
