CREATE TABLE `MAX_USER_MATCHING_SCORE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT NOT NULL,
  `SCORE` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC),
  CONSTRAINT `FK_MAX_USER_MATCHING_SCORE_USER_ID_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `userdb`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);