CREATE TABLE `EMAIL_IMAGE_SOURCE`(
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `EMAIL_NOTIFICATION_LOG_ID` BIGINT NOT NULL,
  `CONTENT_ID` VARCHAR(20) NOT NULL,
  `IMAGE_SOURCE` MEDIUMBLOB NOT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL,
  `UPDATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_EMAIL_IMAGE_SOURCE_NOTIFICATION_LOG_ID_NOTIFICATION_LOG_idx` (`EMAIL_NOTIFICATION_LOG_ID` ASC),
  CONSTRAINT `FK_EMAIL_IMAGE_SOURCE_NOTIFICATION_LOG_ID_NOTIFICATION_LOG`
  FOREIGN KEY (`EMAIL_NOTIFICATION_LOG_ID`)
  REFERENCES `EMAIL_NOTIFICATION_LOG` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
);