ALTER TABLE `userdb`.`CHAT_USER`
ADD COLUMN `FIRST_NAME` VARCHAR(50)NOT NULL AFTER `USER_ID`;
ALTER TABLE `userdb`.`CHAT_USER`
ADD COLUMN `LAST_NAME` VARCHAR(50)NOT NULL AFTER `FIRST_NAME`;

ALTER TABLE `userdb`.`CHAT_MESSAGE`
DROP FOREIGN KEY `FK_CHAT_MESSAGE_USER_ID_USER`;
ALTER TABLE `userdb`.`CHAT_MESSAGE`
DROP INDEX `FK_CHAT_MESSAGE_USER_ID_USER_idx` ;

ALTER TABLE `userdb`.`CHAT_MESSAGE`
DROP COLUMN `USER_ID`;
ALTER TABLE `userdb`.`CHAT_MESSAGE`
ADD COLUMN `CHAT_USER_ID` BIGINT(20) NOT NULL AFTER `CHAT_ID`,
ADD CONSTRAINT `FK_CHAT_MESSAGE_CHAT_USER_ID_CHAT_USER`
FOREIGN KEY (`CHAT_USER_ID`)
REFERENCES `CHAT_USER` (`ID`)
ON DELETE NO ACTION
ON UPDATE NO ACTION;