CREATE TABLE `USER_SESSION` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT NOT NULL,
  `IS_VALID` BIT NOT NULL,
  `SESSION_ID` VARCHAR(50) NOT NULL,
  `IS_EXPIRABLE` BIT NOT NULL,
  `EXPIRATION_TIME` TIMESTAMP NOT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL,
  `UPDATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SESSION_ID_UNIQUE` (`SESSION_ID` ASC));