CREATE TABLE `EMAIL_NOTIFICATION_LOG` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT NULL,
  `EMAIL_TO` VARCHAR(100) NOT NULL,
  `IS_SEND_FAILED` BIT NOT NULL DEFAULT 0,
  `EMAIL_CONTENT_JSON` LONGTEXT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL,
  `UPDATED_DATE` TIMESTAMP NOT NULL,
  `EMAIL_REASON_ID` INT NOT NULL,
  PRIMARY KEY (`ID`));

