server:
  port: 8300

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matchingDB
    username: root
    password: r00t
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect

